# Generated by Django 5.1.7 on 2025-03-15 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_file', models.ImageField(upload_to='originals/')),
                ('processed_file', models.FileField(blank=True, null=True, upload_to='processed/')),
                ('process_type', models.CharField(choices=[('svg', 'SVG'), ('bg_remove', 'Background Removed')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
